# Form implementation generated from reading ui file 'ui/dialog_adjust_contrast.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(637, 207)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.l_contrast = QtWidgets.QLabel(parent=Dialog)
        self.l_contrast.setObjectName("l_contrast")
        self.gridLayout.addWidget(self.l_contrast, 0, 0, 1, 1)
        self.slider_brightness = QtWidgets.QSlider(parent=Dialog)
        self.slider_brightness.setMinimum(-100)
        self.slider_brightness.setMaximum(100)
        self.slider_brightness.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider_brightness.setObjectName("slider_brightness")
        self.gridLayout.addWidget(self.slider_brightness, 1, 2, 1, 1)
        self.spB_brightness = QtWidgets.QSpinBox(parent=Dialog)
        self.spB_brightness.setMinimum(-100)
        self.spB_brightness.setMaximum(100)
        self.spB_brightness.setObjectName("spB_brightness")
        self.gridLayout.addWidget(self.spB_brightness, 1, 4, 1, 1)
        self.l_brightness = QtWidgets.QLabel(parent=Dialog)
        self.l_brightness.setObjectName("l_brightness")
        self.gridLayout.addWidget(self.l_brightness, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 2, 1)
        self.slisder_contrast = QtWidgets.QSlider(parent=Dialog)
        self.slisder_contrast.setMinimum(1)
        self.slisder_contrast.setMaximum(30)
        self.slisder_contrast.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slisder_contrast.setObjectName("slisder_contrast")
        self.gridLayout.addWidget(self.slisder_contrast, 0, 2, 1, 1)
        self.spB_contrast = QtWidgets.QDoubleSpinBox(parent=Dialog)
        self.spB_contrast.setMinimum(0.1)
        self.spB_contrast.setMaximum(3.0)
        self.spB_contrast.setSingleStep(0.1)
        self.spB_contrast.setObjectName("spB_contrast")
        self.gridLayout.addWidget(self.spB_contrast, 0, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 3, 2, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Линейное преобразование"))
        self.l_contrast.setText(_translate("Dialog", "Контрастность"))
        self.l_brightness.setText(_translate("Dialog", "Яркость"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
