# Form implementation generated from reading ui file 'ui/dialog_adjust_contrast.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(637, 207)
        self.main_layout = QtWidgets.QGridLayout(Dialog)
        self.main_layout.setObjectName("main_layout")
        self.label_contrast = QtWidgets.QLabel(parent=Dialog)
        self.label_contrast.setObjectName("label_contrast")
        self.main_layout.addWidget(self.label_contrast, 0, 0, 1, 1)
        self.slider_brightness = QtWidgets.QSlider(parent=Dialog)
        self.slider_brightness.setMinimum(-100)
        self.slider_brightness.setMaximum(100)
        self.slider_brightness.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider_brightness.setObjectName("slider_brightness")
        self.main_layout.addWidget(self.slider_brightness, 1, 2, 1, 1)
        self.spin_brightness = QtWidgets.QSpinBox(parent=Dialog)
        self.spin_brightness.setMinimum(-100)
        self.spin_brightness.setMaximum(100)
        self.spin_brightness.setObjectName("spin_brightness")
        self.main_layout.addWidget(self.spin_brightness, 1, 4, 1, 1)
        self.label_brightness = QtWidgets.QLabel(parent=Dialog)
        self.label_brightness.setObjectName("label_brightness")
        self.main_layout.addWidget(self.label_brightness, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.main_layout.addItem(spacerItem, 0, 1, 2, 1)
        self.slider_contrast = QtWidgets.QSlider(parent=Dialog)
        self.slider_contrast.setMinimum(1)
        self.slider_contrast.setMaximum(30)
        self.slider_contrast.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider_contrast.setObjectName("slider_contrast")
        self.main_layout.addWidget(self.slider_contrast, 0, 2, 1, 1)
        self.spin_contrast = QtWidgets.QDoubleSpinBox(parent=Dialog)
        self.spin_contrast.setMinimum(0.1)
        self.spin_contrast.setMaximum(3.0)
        self.spin_contrast.setSingleStep(0.1)
        self.spin_contrast.setObjectName("spin_contrast")
        self.main_layout.addWidget(self.spin_contrast, 0, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.main_layout.addItem(spacerItem1, 0, 3, 2, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Линейное преобразование"))
        self.label_contrast.setText(_translate("Dialog", "Контрастность"))
        self.label_brightness.setText(_translate("Dialog", "Яркость"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
