# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/dialog_clahe.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(666, 302)
        Dialog.setAutoFillBackground(False)
        Dialog.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 1, 2, 1)
        self.slider_titlleGrid = QtWidgets.QSlider(Dialog)
        self.slider_titlleGrid.setStyleSheet("")
        self.slider_titlleGrid.setMinimum(2)
        self.slider_titlleGrid.setMaximum(64)
        self.slider_titlleGrid.setSingleStep(2)
        self.slider_titlleGrid.setPageStep(2)
        self.slider_titlleGrid.setOrientation(QtCore.Qt.Horizontal)
        self.slider_titlleGrid.setObjectName("slider_titlleGrid")
        self.gridLayout.addWidget(self.slider_titlleGrid, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 3, 2, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 5, 2, 1)
        self.slider_clipLimit = QtWidgets.QSlider(Dialog)
        self.slider_clipLimit.setMaximum(80)
        self.slider_clipLimit.setSingleStep(1)
        self.slider_clipLimit.setPageStep(1)
        self.slider_clipLimit.setOrientation(QtCore.Qt.Horizontal)
        self.slider_clipLimit.setObjectName("slider_clipLimit")
        self.gridLayout.addWidget(self.slider_clipLimit, 1, 2, 1, 1)
        self.spB_titleGrid = QtWidgets.QSpinBox(Dialog)
        self.spB_titleGrid.setMinimum(2)
        self.spB_titleGrid.setMaximum(64)
        self.spB_titleGrid.setSingleStep(2)
        self.spB_titleGrid.setProperty("value", 2)
        self.spB_titleGrid.setObjectName("spB_titleGrid")
        self.gridLayout.addWidget(self.spB_titleGrid, 2, 4, 1, 1)
        self.spB_clipLimit = QtWidgets.QDoubleSpinBox(Dialog)
        self.spB_clipLimit.setMaximum(40.0)
        self.spB_clipLimit.setSingleStep(0.5)
        self.spB_clipLimit.setObjectName("spB_clipLimit")
        self.gridLayout.addWidget(self.spB_clipLimit, 1, 4, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Настройки CLAHE"))
        self.label_2.setText(_translate("Dialog", "Размер сетки"))
        self.label.setText(_translate("Dialog", "Порог ограничения контраста"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
