# Form implementation generated from reading ui file 'ui/dialog_clahe.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(632, 229)
        Dialog.setAutoFillBackground(False)
        Dialog.setStyleSheet("")
        self.main_layout = QtWidgets.QGridLayout(Dialog)
        self.main_layout.setObjectName("main_layout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.main_layout.addItem(spacerItem, 1, 1, 2, 1)
        self.slider_tile_grid = QtWidgets.QSlider(parent=Dialog)
        self.slider_tile_grid.setStyleSheet("")
        self.slider_tile_grid.setMinimum(2)
        self.slider_tile_grid.setMaximum(64)
        self.slider_tile_grid.setSingleStep(2)
        self.slider_tile_grid.setPageStep(2)
        self.slider_tile_grid.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider_tile_grid.setObjectName("slider_tile_grid")
        self.main_layout.addWidget(self.slider_tile_grid, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.main_layout.addItem(spacerItem1, 1, 3, 2, 1)
        self.label_screenshot_title = QtWidgets.QLabel(parent=Dialog)
        self.label_screenshot_title.setObjectName("label_screenshot_title")
        self.main_layout.addWidget(self.label_screenshot_title, 2, 0, 1, 1)
        self.label_record_format = QtWidgets.QLabel(parent=Dialog)
        self.label_record_format.setObjectName("label_record_format")
        self.main_layout.addWidget(self.label_record_format, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.main_layout.addItem(spacerItem2, 1, 5, 2, 1)
        self.slider_clip_limit = QtWidgets.QSlider(parent=Dialog)
        self.slider_clip_limit.setMaximum(80)
        self.slider_clip_limit.setSingleStep(1)
        self.slider_clip_limit.setPageStep(1)
        self.slider_clip_limit.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider_clip_limit.setObjectName("slider_clip_limit")
        self.main_layout.addWidget(self.slider_clip_limit, 1, 2, 1, 1)
        self.spin_tile_grid = QtWidgets.QSpinBox(parent=Dialog)
        self.spin_tile_grid.setMinimum(2)
        self.spin_tile_grid.setMaximum(64)
        self.spin_tile_grid.setSingleStep(2)
        self.spin_tile_grid.setProperty("value", 2)
        self.spin_tile_grid.setObjectName("spin_tile_grid")
        self.main_layout.addWidget(self.spin_tile_grid, 2, 4, 1, 1)
        self.spin_clip_limit = QtWidgets.QDoubleSpinBox(parent=Dialog)
        self.spin_clip_limit.setMaximum(40.0)
        self.spin_clip_limit.setSingleStep(0.5)
        self.spin_clip_limit.setObjectName("spin_clip_limit")
        self.main_layout.addWidget(self.spin_clip_limit, 1, 4, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Настройки CLAHE"))
        self.label_screenshot_title.setText(_translate("Dialog", "Размер сетки"))
        self.label_record_format.setText(_translate("Dialog", "Порог ограничения контраста"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
