# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1359, 907)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.group_contrast_enhancement = QtWidgets.QGroupBox(self.centralwidget)
        self.group_contrast_enhancement.setObjectName("group_contrast_enhancement")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.group_contrast_enhancement)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.group_contrast_enhancement)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.group_contrast_enhancement, 1, 1, 1, 1)
        self.videoFrame = QtWidgets.QLabel(self.centralwidget)
        self.videoFrame.setText("")
        self.videoFrame.setObjectName("videoFrame")
        self.gridLayout.addWidget(self.videoFrame, 0, 0, 2, 1)
        self.group_grabling_video = QtWidgets.QGroupBox(self.centralwidget)
        self.group_grabling_video.setObjectName("group_grabling_video")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.group_grabling_video)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bt_open_camera = QtWidgets.QPushButton(self.group_grabling_video)
        self.bt_open_camera.setObjectName("bt_open_camera")
        self.gridLayout_2.addWidget(self.bt_open_camera, 2, 0, 1, 1)
        self.bt_stop_grabling = QtWidgets.QPushButton(self.group_grabling_video)
        self.bt_stop_grabling.setObjectName("bt_stop_grabling")
        self.gridLayout_2.addWidget(self.bt_stop_grabling, 3, 1, 1, 1)
        self.bt_start_grabling = QtWidgets.QPushButton(self.group_grabling_video)
        self.bt_start_grabling.setObjectName("bt_start_grabling")
        self.gridLayout_2.addWidget(self.bt_start_grabling, 3, 0, 1, 1)
        self.bt_update_cameras = QtWidgets.QPushButton(self.group_grabling_video)
        self.bt_update_cameras.setObjectName("bt_update_cameras")
        self.gridLayout_2.addWidget(self.bt_update_cameras, 1, 0, 1, 2)
        self.c_list_cameras = QtWidgets.QComboBox(self.group_grabling_video)
        self.c_list_cameras.setObjectName("c_list_cameras")
        self.gridLayout_2.addWidget(self.c_list_cameras, 0, 1, 1, 1)
        self.bt_stop_write = QtWidgets.QPushButton(self.group_grabling_video)
        self.bt_stop_write.setObjectName("bt_stop_write")
        self.gridLayout_2.addWidget(self.bt_stop_write, 4, 1, 1, 1)
        self.l_list_cameras = QtWidgets.QLabel(self.group_grabling_video)
        self.l_list_cameras.setObjectName("l_list_cameras")
        self.gridLayout_2.addWidget(self.l_list_cameras, 0, 0, 1, 1)
        self.bt_close_camera = QtWidgets.QPushButton(self.group_grabling_video)
        self.bt_close_camera.setObjectName("bt_close_camera")
        self.gridLayout_2.addWidget(self.bt_close_camera, 2, 1, 1, 1)
        self.bt_start_write = QtWidgets.QPushButton(self.group_grabling_video)
        self.bt_start_write.setObjectName("bt_start_write")
        self.gridLayout_2.addWidget(self.bt_start_write, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.group_grabling_video, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1359, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.group_contrast_enhancement.setTitle(_translate("MainWindow", "Настройки улучшения контраста"))
        self.label.setText(_translate("MainWindow", " Пока ничего"))
        self.group_grabling_video.setTitle(_translate("MainWindow", "Настройки захвата кадра с камеры"))
        self.bt_open_camera.setText(_translate("MainWindow", "Подключиться к камере"))
        self.bt_stop_grabling.setText(_translate("MainWindow", "Завершить захват кадров"))
        self.bt_start_grabling.setText(_translate("MainWindow", "Начать захват кадров"))
        self.bt_update_cameras.setText(_translate("MainWindow", "Обновить список камер"))
        self.bt_stop_write.setText(_translate("MainWindow", "Завершить запись"))
        self.l_list_cameras.setText(_translate("MainWindow", "Доступные камеры:"))
        self.bt_close_camera.setText(_translate("MainWindow", "Отключиться от камеры"))
        self.bt_start_write.setText(_translate("MainWindow", "Запись в файл"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
