# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(911, 686)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.group_contrast_enhancement = QtWidgets.QGroupBox(self.centralwidget)
        self.group_contrast_enhancement.setObjectName("group_contrast_enhancement")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.group_contrast_enhancement)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.group_contrast_enhancement)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.group_contrast_enhancement, 1, 1, 1, 1)
        self.videoFrame = QtWidgets.QLabel(self.centralwidget)
        self.videoFrame.setText("")
        self.videoFrame.setObjectName("videoFrame")
        self.gridLayout.addWidget(self.videoFrame, 0, 0, 2, 1)
        self.group_grabling_video = QtWidgets.QGroupBox(self.centralwidget)
        self.group_grabling_video.setObjectName("group_grabling_video")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.group_grabling_video)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.l_list_cameras = QtWidgets.QLabel(self.group_grabling_video)
        self.l_list_cameras.setObjectName("l_list_cameras")
        self.gridLayout_2.addWidget(self.l_list_cameras, 0, 0, 1, 1)
        self.bt_start_record = QtWidgets.QPushButton(self.group_grabling_video)
        self.bt_start_record.setObjectName("bt_start_record")
        self.gridLayout_2.addWidget(self.bt_start_record, 3, 0, 1, 1)
        self.bt_start_capture = QtWidgets.QPushButton(self.group_grabling_video)
        self.bt_start_capture.setObjectName("bt_start_capture")
        self.gridLayout_2.addWidget(self.bt_start_capture, 2, 0, 1, 1)
        self.c_list_cameras = QtWidgets.QComboBox(self.group_grabling_video)
        self.c_list_cameras.setObjectName("c_list_cameras")
        self.gridLayout_2.addWidget(self.c_list_cameras, 0, 1, 1, 1)
        self.bt_stop_record = QtWidgets.QPushButton(self.group_grabling_video)
        self.bt_stop_record.setObjectName("bt_stop_record")
        self.gridLayout_2.addWidget(self.bt_stop_record, 3, 1, 1, 1)
        self.bt_update_cameras = QtWidgets.QPushButton(self.group_grabling_video)
        self.bt_update_cameras.setObjectName("bt_update_cameras")
        self.gridLayout_2.addWidget(self.bt_update_cameras, 1, 0, 1, 2)
        self.bt_stop_capture = QtWidgets.QPushButton(self.group_grabling_video)
        self.bt_stop_capture.setObjectName("bt_stop_capture")
        self.gridLayout_2.addWidget(self.bt_stop_capture, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.group_grabling_video, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 911, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.group_contrast_enhancement.setTitle(_translate("MainWindow", "Настройки улучшения контраста"))
        self.label.setText(_translate("MainWindow", " Пока ничего"))
        self.group_grabling_video.setTitle(_translate("MainWindow", "Настройки захвата кадра с камеры"))
        self.l_list_cameras.setText(_translate("MainWindow", "Доступные камеры:"))
        self.bt_start_record.setText(_translate("MainWindow", "Запись в файл"))
        self.bt_start_capture.setText(_translate("MainWindow", "Начать захват кадров"))
        self.bt_stop_record.setText(_translate("MainWindow", "Завершить запись"))
        self.bt_update_cameras.setText(_translate("MainWindow", "Обновить список камер"))
        self.bt_stop_capture.setText(_translate("MainWindow", "Завершить захват кадров"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
